coverage:
  range: 50..80
  round: down
  precision: 2

ignore:
  - "*_test.go"
  - "vendor"
  - "cmd"
  - "dynamo"
  - "redis"
  - "fx"
  - "http"
  - "sqs"
  - "kafka"

fixes:
  - "github.com/xmidt-org/ears/::"
