extensions:
  health_check:
    endpoint: "localhost:13133"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:55680"
      http:
        endpoint: "localhost:55681"

processors:
  batch:
    timeout: 10s

exporters:
  datadog/api:
    hostname: earstesthost
    env: local
    service: ears
    version: v1.1
    tags:
      - env:testlocal
      - team:va
      - region:bwregion
      - role:bwrole
    api:
      key: 

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/api]
    metrics:
      receivers: [otlp]
      exporters: [datadog/api]
