# SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - MAINTAINERS.md
      - LICENSE
      - NOTICE
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: xmidt-org/.github/.github/workflows/go-ci.yml@go-ci-v1
    with:
      sonarcloud-exclusions: '**/*_test.go,**/*testing.go,**/testing_mock.go,**/vendor/**,**/cmd/**,**/test/**,**/fx/**,**/dynamo/**,**/redis/**,**/http/**,**/sqs/**,**/kafka/**,**/s3/**'
      lint-skip: true
      style-skip: true
    secrets: inherit
